name: demeter-docker-image-ci

on:
  push:
    branches: [ master ]
  #   branches: [ master, feature-/*, hotfix-/* ] # move to another workflow
  # pull_request: # move to another workflow
  #   branches: [ master, feature-/*, hotfix-/* ] # move to another workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: demeter
  RUN_REGION: asia-east1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

    # Authorize
    # https://github.com/google-github-actions/setup-gcloud#service-account-key-json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    # https://github.com/google-github-actions/setup-gcloud
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '354.0.0'
        
    # Print gcloud info
    - name: Info
      run: gcloud info

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest"

